export type arcCapType = "butt" | "round" | "-round"
export type textAlignType = "left" | "center" | "right"
export type textBaselineType = "top" | "middle" | "bottom"
export type lineCapType = "butt" | "round" | "square"
export type lineJoinType = "miter" | "bevel" | "round"